### ISSUE TITLE
忘記密碼流程設計

### ISSUE THREAD

**Issue by ChiMiLin** [Ssssss-project/patyclub-server#4]
目前規劃

1. 使用者點擊忘記密碼時，輸入email，後端發送重設密碼信供使用者重設密碼
2. 後端接收到email時，至DB查詢此email對應的使用者
3. 後端產生一識別雜湊，並儲存至DB中對應User資訊
4. 傳送內含LINK(後面串上識別碼)的EMAIL給使用者，前端再將此識別碼自URL拆解下來與新密碼一同回傳後端以修改密碼

識別碼 : 帳號雜湊? (帳號+時間戳記)雜湊? (帳號+時間戳記)加密? 

問題點

1. 此識別碼是否可能被冒用
2. 此識別碼該如何組成以增加安全性
3. 此識別碼如何設計有效期限

**Comment by HunagYuCheng** [comment]
api 測試成功，目前問題前後端參數不一致，暫時將後端修改為User Object來做測試
1. 需要增加若無此email的回應代碼
2. 需要重設密碼api

**Comment by ChiMiLin** [comment]
目前預計模式

- 忘記密碼時，點選忘記密碼並填入email，後端將發送帶Token的mail供使用者填寫新密碼
- 此token會在發送mail時寫至DB，並記錄token產生時間
- 當使用者欲更改密碼時，前端將更改後密碼以及Token傳回後端，並由後端至DB檢查使否有符合條件之token(未逾時且相符Token)
- 若符合則修改其密碼，反之則回覆錯誤訊息(逾時/無相符Token)

另
曾考慮以JWT做時效性驗證，具體實行方式需討論
