### ISSUE TITLE
討論關於ActionCode規則與定義

### ISSUE THREAD

**Issue by ChiMiLin** [Ssssss-project/patyclub-server#6]
依上次決議，包含API與資料面的狀態都以Action Code顯示，但若單獨討論驗證失敗此狀態，API的Token驗證失敗以及帳號密碼的資料端驗證失敗，雖然同屬驗證失敗但面向不同，因此提議新增一區間專門定義為資料面狀態碼，用以區分API Action Code 以及 Data Action Code。

例如 : 
驗證失敗 API : 401 Data : 701

**Comment by xiouchin32** [comment]
常用感覺是
登入錯誤 或是權限錯誤 皆是 403 forbidden ，如果是要區分是登入錯誤還是權限錯誤 ，則可以利用response message ，讓前端可以顯示 是什麼樣的403

然後如果token失敗  通常是 401 Unauthorized 

我是這樣想的~

**Comment by ChiMiLin** [comment]
那如果是在資料庫中找不到資源的這種是用404 found嗎?
例如說是要找特定活動，但卻輸入了不存在的活動ID

**Comment by ChiMiLin** [comment]
結論
經所有事件反應於 StatusCode 關於 StatusCode 的規則於事件遭遇時待討論

若有相同事件但屬相同情境時，StatusCode應一樣，並於Message內容區分
